travis:
  secure:
    BINSTAR_TOKEN: YW859jeofLPMzKV+g0PFsVzpcgVq9HnZ6pZ448wweFWtx6o0fUXsNC3yij5f4l4MtWfcua6IcrKsCcS0aG0zOMP7BdacJZvo6czCI3CJnFnMN0s2buKbPd/T27DDRmEgZJE8wTa3+VnUkUNFzF4f8Ax7+WIDCLqQM3rCuuMaCOHASIJAnUEBWNYmxAZ/wTUCkXKH9cPl4vYZS4jmOafHviwpjVjyv73tjq+WOaRCx93tLo1bjfu8gjZts6TYmvYM2HyAZRjZR3HzxsR3dLI8woEL0OyWvjpXocCvJSb8Tfc/OI/Wv7HcJ/gzp0s8jo2sqHexxeq+jQs2eqeavxvqyvCAG27Vs23D5iA0CD21XU3/1/zdbMdt0u6Yew0Z2NjkGMmngCC24itRz7RGuyyAgi99zjvIwCZgkEQA3X84Q+ipEPaw+/sMBEuyTSvmeRLDeWGNt50jhV4dAVuFEQnvrSkX1vOIJY1N8pareyG7ggzHxriy83XVbULrwsBm0pUMO4XGwwWgtCulAVp8T3zHU2Lc7IYgK26IEWfOT27d19bpZHuueRBQ+TX8/vQpthnZW+/PwcY2uNydoXvQM1MM4N9vHi3nlunw4tsaSzQQuSiaMTmX119gqKTRFqH9TorUX2bwwiAEg7db72KBW53HkD40dIlXL0blr2R0QoUlZTE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
