travis:
  secure:
    BINSTAR_TOKEN: lNRD1XYh8XhwGyq6enPUEKwkP8hha+7oJPtsVh7+AxovgYMvt9lnANc4rcl4BO4hY4B75c0Y/VPFCL549cz9tTF0sQBwNwEP44i2E/FfieKqYa9s8jMd2aSahJ5mKznITM5tFXa3D9soA18h7yh9XpdATV3EzNvH5MIK9y8u8teuo33xmLeS3zMmJYUk2Qzb77wL9jo9yadybFZ13/S+SVUVO2h2bHZpT7gcTqrU+Ij2w4lPrDMxHSL7WZS3SbqVy9pyorPZbEV3qblujbtG+kHo8nKlSdY6ys6OzrNKT+v3NNeRa7fbGPmMiCWhVQ3uXRHxAv6Z+48KXnyrB5D2nvCb89fB7Io9BwSHcWYfSlXwYy2jRgLqKOO4BfWX96eZ4cEq9w+xsNQXGOZxPqCWwygSfzfFo2m+xmwiLACE3rZ4HOYwsLUuEVSq3rdRVDy54EpkH01ozPGN8rFRLbDHmpLiT551mSu8WEsOTNCqYs8Cj9fINlJuPtckW/W6Y2NSXXxk61fIg88Gy64othZcAlIe5CuykIz0d0Es3n1T8rYveYzEfdNbdD9tHUimrm4rBcnnkdz66EFNkqpwRbkHJv81/vmleziY6lVnlijMxSkE7bAK6NLRA1DSyE0PRbhZfjcrp6Od3iZzzvxX1qfFFsAVu+KVNsrGd6qB8b6nung=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
